/**
 * The JavaScript solar position against the Python one, case by case.
 *
 * web/src/sun.ts is a port of backend/suncokret/sun.py. Two implementations of
 * the same series in two languages is exactly the arrangement that drifts
 * silently, so sun-reference.json is generated by the Python module and
 * committed, and this test fails the build if the port stops agreeing with it.
 *
 * It matters here more than it would elsewhere: the browser decides what the
 * carpet says using this file, and the bundle was built using the other one.
 */

import { describe, expect, it } from "vitest";

import reference from "./sun-reference.json";
import { incidenceCosine, solarPosition, sunVector } from "../src/sun";

// Two implementations of the same closed-form series in double precision should
// agree to far better than this. The tolerance is here to absorb the rounding
// in the committed file, not real disagreement.
const TOLERANCE_DEG = 1e-6;

describe("solar position agrees with the Python implementation", () => {
  it("has a reference set worth trusting", () => {
    expect(reference.cases.length).toBeGreaterThan(100);
    const places = new Set(reference.cases.map((c) => c.place));
    expect(places.size).toBeGreaterThan(3);
  });

  for (const c of reference.cases) {
    it(`${c.place} ${new Date(c.t * 1000).toISOString()}`, () => {
      const got = solarPosition(c.t, c.lat, c.lon);
      expect(got.elevation).toBeCloseTo(c.elevation, 6);

      // Azimuth wraps at 360, so compare the shortest angle between the two
      // rather than the raw difference.
      const delta = Math.abs(((got.azimuth - c.azimuth + 540) % 360) - 180);
      expect(delta).toBeLessThan(TOLERANCE_DEG);
    });
  }
});

describe("derived quantities", () => {
  it("sun vectors are unit length", () => {
    for (const c of reference.cases.slice(0, 20)) {
      const v = sunVector(solarPosition(c.t, c.lat, c.lon));
      const length = Math.hypot(v[0], v[1], v[2]);
      expect(length).toBeCloseTo(1, 12);
    }
  });

  it("a horizontal plane sees the sine of the elevation", () => {
    for (const c of reference.cases.slice(0, 40)) {
      const p = solarPosition(c.t, c.lat, c.lon);
      expect(incidenceCosine(p, 0, 0)).toBeCloseTo(
        Math.sin((p.elevation * Math.PI) / 180),
        12,
      );
    }
  });

  it("incidence is the dot product of the beam and the plane normal", () => {
    const tilt = 35;
    const azimuth = 200;
    const t = (tilt * Math.PI) / 180;
    const a = (azimuth * Math.PI) / 180;
    const normal = [
      Math.sin(t) * Math.sin(a),
      Math.sin(t) * Math.cos(a),
      Math.cos(t),
    ];
    for (const c of reference.cases.slice(0, 40)) {
      const p = solarPosition(c.t, c.lat, c.lon);
      const v = sunVector(p);
      const dot = v[0] * normal[0] + v[1] * normal[1] + v[2] * normal[2];
      expect(incidenceCosine(p, tilt, azimuth)).toBeCloseTo(dot, 12);
    }
  });

  it("the sun is behind a plane that faces away from it", () => {
    // Zagreb, midsummer noon: a north-facing steep roof gets nothing.
    const p = solarPosition(Date.UTC(2020, 5, 21, 10, 0) / 1000, 45.815, 15.9819);
    expect(p.elevation).toBeGreaterThan(50);
    expect(incidenceCosine(p, 70, 0)).toBeLessThan(0);
    expect(incidenceCosine(p, 30, 180)).toBeGreaterThan(0.5);
  });
});
